export const SOHOSAI_COM = "https://sohosai.com/"
export const TWITTER_KIKAKURENRAKUN = "https://twitter.com/kikakurenrakun/"
export const INSTAGRAM = "https://www.instagram.com/sohosai/"
export const FACEBOOK = "https://www.facebook.com/sohosai/"
export const STAGE_GUIDANCE_URL = "https://youtu.be/q91_2m5ym88"
export const GENERAL_PROJECT_GUIDANCE_URL = "https://youtu.be/IGcznNm-jCo"
