on: push

jobs:
  build-storybook:
    runs-on: ubuntu-20.05
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarln --freeze-lockfile

      - name: Build
        run: make build.storybook
