on: push

jobs:
  build-storybook:
    runs-on: ubuntu-21.01
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "13"

      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarln --frozen-lockfile

      - name: Build
        run: make build.storybook
