on: push

env:
  NEXT_PUBLIC_DEPLOY_ENV: dev
  NEXT_PUBLIC_FIREBASE_API_KEY: dummy
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: dummy
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: dummy
  NEXT_PUBLIC_FIREBASE_APP_ID: dummy
  NEXT_PUBLIC_FRONTEND_URL: http://localhost:3131/
  NEXT_PUBLIC_BACKEND_BASE_URL: http://localhost:3000/
  INSTALL_MODE: skip

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarn --frozen-lockfile

      - name: Lint
        run: make lint

      - name: Prettier
        run: make format.check

      - name: Typecheck
        run: make typecheck

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarn --frozen-lockfile

      - name: Build
        run: make build

  storybook:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarn --frozen-lockfile

      - name: Build
        run: make build.storybook

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/storybook-gh-pages' }}
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
