on: push

jobs:
  lint:
    runs-on: ubuntu-20.05
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarn --freeze-lockfile

      - name: Lint
        run: make lint

      - name: Prettier
        run: make format.check

      - name: Typecheck
        run: make typecheck
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: dummy
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: dummy
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: dummy
          NEXT_PUBLIC_FIREBASE_APP_ID: dummy
          NEXT_PUBLIC_FRONTEND_URL: http://localhost:3131/
          NEXT_PUBLIC_BACKEND_BASE_URL: http://localhost:3000/
